version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /home/phuocdai/Retrieval-System/qdrant/storage:/qdrant/storage  # Sử dụng bind mount
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
      QDRANT__STORAGE__STORAGE_PATH: /qdrant/storage
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__LOG_LEVEL: INFO
    networks:
      - aienthusiasm-netowrk

networks:
  aienthusiasm-netowrk:
    driver: bridge